# Generated by Django 5.1.6 on 2025-04-13 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMaterial',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False, verbose_name='SL.NO')),
                ('description', models.TextField(verbose_name='DESCRIPITION')),
                ('part_no', models.CharField(max_length=100, unique=True, verbose_name='PART NO')),
                ('unit', models.CharField(max_length=50, verbose_name='UNIT')),
                ('supplier_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SUPPLIER RATE')),
                ('seipl_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SEIPL RATE')),
                ('category', models.CharField(blank=True, choices=[], max_length=100, verbose_name='CATEGORY')),
                ('sub_category', models.CharField(blank=True, choices=[], max_length=100, verbose_name='SUB CATEGORY')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SALE RATE')),
                ('total_received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TOTAL RECEIVED QTY')),
                ('vendor_issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VENDOR ISSUED QTY')),
                ('vendor_received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VENDOR RECEIVED QTY')),
                ('board_issue_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='BOARD ISSUE QTY')),
                ('avl_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AVL STOCK')),
                ('avl_stock_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AVL STOCK VALUE')),
                ('billing_qty_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BILLING QTY DIFF')),
                ('total_received_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TOTAL RECEIVED COST')),
                ('total_billed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TOTAL BILLED COST')),
                ('cost_diff', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='COST DIFF')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='supplier_details.supplier', verbose_name='VENDOR NAME')),
            ],
            options={
                'verbose_name': 'Master Material',
                'verbose_name_plural': 'Master Materials',
                'ordering': ['sl_no'],
                'indexes': [models.Index(fields=['part_no'], name='master_mate_part_no_f4645b_idx'), models.Index(fields=['category', 'sub_category'], name='master_mate_categor_a68875_idx')],
            },
        ),
    ]
